### PR TITLE
WIP: bugfix(): fixing in.Body.DeepCopyReadCloser undefined

### PR DESCRIPTION
**Pull request by AniketKul**
This PR fixes https://github.com/ocibuilder/ocibuilder/issues/16

### CODE REVIEW

**Comment by VaibhavPage** [comment]
I don't think this PR is required.

**Comment by AniketKul** [comment]
> I don't think this PR is required.

@VaibhavPage - `make test` fails at present because of this. We were not using types.ImageBuildResponse from types.go file so needed to remove that.

**Comment by AniketKul** [comment]
Now it is failing because of the following error: 

```
github.com/ocibuilder/ocibuilder/pkg/client/ocibuilder/clientset/versioned/typed/ocibuilder/v1alpha1
pkg/client/ocibuilder/clientset/versioned/typed/ocibuilder/v1alpha1/ocibuilder_client.go:72:45: scheme.Codecs.WithoutConversion undefined (type serializer.CodecFactory has no field or method WithoutConversion)
```

**Comment by VaibhavPage** [comment]
We shouldn't have ImageBuildResponse in types.go

**Comment by artbegolli** [comment]
All tests have been fixed in the #1

**Comment by AniketKul** [comment]
> We shouldn't have ImageBuildResponse in types.go. The master branch has the updated code.

haha! @VaibhavPage - looks like you merged that change into master already. Cool!

**Comment by AniketKul** [comment]
Marking it stale!

**Pull request closed without merging**
