### PR TITLE
feat(contexts): support contexts for local, s3 and git

### LINKED ISSUE #40: Support different build contexts
**Is your feature request related to a problem? Please describe.**
To build an image, you need the context/filesystem to work with. The CLI only supports local context meaning local filesystem which is not sufficient as there may be scenarios where the context is not available locally.

**Describe the solution you'd like**
Support context stored on - 

- [x] Local filesystem
- [x] S3
- [x] Git
- [x] Azure Blob Storage
- [x] GCP PubSub
- [x] Alibaba Cloud OSS

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by VaibhavPage**
closes #40

### CODE REVIEW

**Comment by artbegolli** [comment]
This ready to review?

**Comment by VaibhavPage** [comment]
It should be as soon as I resolve the conflicts

**Comment by VaibhavPage** [comment]
@artbegolli, as discussed, left the commands more or less intact. Also, feel free to move files directly under "pkg" to their respective packages.

**Comment by artbegolli** [comment]
Some notes - 

- The path to the dockerfile is relative to the build context - the docker daemon seems to expect the Dockerfile to be within whatever build context has been specified, the path to the Dockerfile and the path to the context are not decoupled.

- This is okay for a local context, we can generate the Dockerfile in whatever specified directory and then tar the context. For other contexts this would require pulling the context from whatever external resource, extracting it, adding the Dockerfile and then repackaging it.

On the postiive this makes cleanup easier, we'll only have to cleanup the context tar which has a standard name and location and not the generated Dockerfile as well.

**Comment by artbegolli** [comment]
closes #79

**Pull request merged**
